### ISSUE TITLE
Add a filter to scan only wellknown protocols [UDP, TCP, ...]

### ISSUE THREAD

**Issue by kursatkobya** [kursatkobya/libfrizz#46]
Currently port scan has availability to filter between port number range. It would be useful to scan depending on protocol type.
check nmap parameters before implementing this https://techtalk.gfi.com/scanning-open-ports-in-windows-part-3-nmap/

tip : https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

*AC*
* scan only UDP ports 
* scan only TCP ports

**Comment by ozkanpakdil** [comment]
https://github.com/nmap/nmap/blob/master/nmap-services
https://svn.nmap.org/nmap/nmap-services

**Comment by kursatkobya** [comment]
> https://github.com/nmap/nmap/blob/master/nmap-services https://svn.nmap.org/nmap/nmap-services better then "awk '$2~/tcp$/' /usr/share/nmap/nmap-services | sort -r -k3 | head -n 1000 | tr -s ' ' | cut -d '/' -f1 | sed 's/\S*\s*(\S*).*/\1,/'" although ![image](https://user-images.githubusercontent.com/604405/140607356-50b684e5-1753-48d2-95f7-eeb8896dacf8.png)

yeah, fair i will change the comment in next update.
